version: '3.7'
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
  nginx:
    image: nginx:1.23.1-alpine
    volumes:
      - ./config/docker/nginx/conf.d/local.conf:/etc/nginx/conf.d/default.conf

